# Generated by Django 3.2.5 on 2021-07-16 19:05

import cloudinary.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('bio', models.TextField(blank=True, default='My Bio', max_length=500)),
                ('contact', models.CharField(blank=True, max_length=60)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 7, 16, 19, 5, 3, 566895, tzinfo=utc))),
            ],
        ),
    ]
