# Generated by Django 3.2.5 on 2021-07-17 10:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_alter_profile_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 10, 50, 51, 183786, tzinfo=utc)),
        ),
    ]
