# Generated by Django 3.2.5 on 2021-07-17 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_alter_profile_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 10, 52, 37, 125231, tzinfo=utc)),
        ),
    ]
